2025-07-30 18:48:05 modelling.py [INFO] MLflow setup for DagsHub https://dagshub.com/DeployCamp16/Fraud-Detection-System.mlflow completed.
2025-07-30 18:48:05 modelling.py [INFO] Loading data from: ../data/processed/fraud_detection_processed.csv
2025-07-30 18:48:05 modelling.py [INFO] Data loaded and split. Train: (1212, 9), Test: (304, 9)
2025-07-30 18:48:06 modelling.py [ERROR] An error occurred when training model: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
Traceback (most recent call last):
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\training\modelling.py", line 226, in main
    run_id, metrics, cv_accuracy = model_train(
                                   ^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\training\modelling.py", line 92, in model_train
    with mlflow.start_run(run_name=f'{model_name}_run_ci') as run:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\.venv\Lib\site-packages\mlflow\tracking\fluent.py", line 446, in start_run
    active_run_obj = client.create_run(
                     ^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\.venv\Lib\site-packages\mlflow\tracking\client.py", line 393, in create_run
    return self._tracking_client.create_run(experiment_id, start_time, tags, run_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\.venv\Lib\site-packages\mlflow\tracking\_tracking_service\client.py", line 169, in create_run
    return self.store.create_run(
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 212, in create_run
    response_proto = self._call_endpoint(CreateRun, req_body)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\.venv\Lib\site-packages\mlflow\store\tracking\rest_store.py", line 82, in _call_endpoint
    return call_endpoint(self.get_host_creds(), endpoint, method, json_body, response_proto)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 370, in call_endpoint
    response = verify_rest_response(response, endpoint)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ACER\Documents\USU\Semester6\deploycamp\Fraud-Detection-System\.venv\Lib\site-packages\mlflow\utils\rest_utils.py", line 246, in verify_rest_response
    raise MlflowException(
mlflow.exceptions.MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 403 != 200. Response body: ''
